services:
  _defaults:
    autowire: true
    autoconfigure: true

  # https://symfony.com/doc/current/components/security/authentication.html#authentication-events
  fail2ban_authentication_success_listener:
    class: KarolKrupa\Fail2banBundle\EventListener\AuthenticationSuccessListener
    arguments:
      $config: []
    tags:
      - name: kernel.event_listener
        event: security.authentication.success
        method: 'onAuthenticationSuccess'

  fail2ban_authentication_failure_listener:
    class: KarolKrupa\Fail2banBundle\EventListener\AuthenticationFailureListener
    tags:
      - name: kernel.event_listener
        event: security.authentication.failure
        method: 'onAuthenticationFailure'

  fail2ban_storage_provider:
    class: KarolKrupa\Fail2banBundle\DefaultStorageProvider

  KarolKrupa\Fail2banBundle\StorageProvider:
    alias: fail2ban_storage_provider

  fail2ban_user_handler:
    class: KarolKrupa\Fail2banBundle\DefaultUserHandler

  KarolKrupa\Fail2banBundle\UserHandler:
    alias: fail2ban_user_handler

  fail2ban_config_provider:
    class: \KarolKrupa\Fail2banBundle\DefaultConfigProvider
    arguments:
      $config: []

  KarolKrupa\Fail2banBundle\ConfigProvider:
    alias: fail2ban_config_provider